# EK-SCU35-G board configuration
# Device: Spartan UltraScale+ XCSU35P-2SBVB625E
# Part string verified via: vivado -mode tcl → get_parts *xcsu35p*
PART       := xcsu35p-sbvb625-2-e
TOP        := emu_top
XDC_DIR    := xdc
COMMON_DIR := ../common

include $(COMMON_DIR)/Makefile.include
